-- strict

--  DROP TABLE public.project CASCADE;
--  DROP TABLE public.taskstatusbars CASCADE; 
-- DROP TABLE public.tasks CASCADE;
-- DROP TABLE public.people CASCADE;
-- DROP TABLE public.projectstatus CASCADE;
-- DROP TABLE public.permissions CASCADE;

-- MySQL Script generated by MySQL Workbench
-- Thu 16 Feb 2017 16:13:33 SAST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema qrumb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema qrumb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `qrumb` ;
USE `qrumb` ;

-- -----------------------------------------------------
-- Table `qrumb`.`people`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qrumb`.`people` (
  `uid` INT NOT NULL AUTO_INCREMENT,
  `uname` VARCHAR(20) NOT NULL,
  `uemail` VARCHAR(72) NOT NULL,
  `upassword` VARCHAR(100) NULL DEFAULT NULL,
  `role` CHAR(0) NULL DEFAULT NULL,
  UNIQUE INDEX (`uname` ASC),
  UNIQUE INDEX (`uemail` ASC),
  PRIMARY KEY (`uid`));


-- -----------------------------------------------------
-- Table `qrumb`.`projectstatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qrumb`.`projectstatus` (
  `id` SMALLINT NOT NULL AUTO_INCREMENT,
  `status` CHAR NOT NULL,
  `name` VARCHAR(10) NOT NULL,
  `descr` VARCHAR(200) NULL DEFAULT NULL,
  UNIQUE INDEX (`status` ASC),
  UNIQUE INDEX (`name` ASC),
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `qrumb`.`project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qrumb`.`project` (
  `pid` INT NOT NULL AUTO_INCREMENT,
  `pname` VARCHAR(30) NOT NULL,
  `date_created` DATE NOT NULL,
  `date_modified` DATE NOT NULL,
  `status` CHAR NULL DEFAULT NULL,
  `uid` INT NOT NULL,
  `pdesc` VARCHAR(200) NULL DEFAULT NULL,
  `date_expiring` DATE NOT NULL,
  PRIMARY KEY (`pid`, `uid`),
  INDEX `uid_idx` (`uid` ASC),
  CONSTRAINT `uid`
    FOREIGN KEY (`uid`)
    REFERENCES `qrumb`.`people` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `status`
    FOREIGN KEY ()
    REFERENCES `qrumb`.`projectstatus` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `qrumb`.`taskstatusbars`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qrumb`.`taskstatusbars` (
  `tid` INT NOT NULL AUTO_INCREMENT,
  `tname` VARCHAR(20) NOT NULL,
  `pid` INT NOT NULL,
  `pos` INT NOT NULL,
  `uid` INT NOT NULL,
  PRIMARY KEY (`tid`, `uid`),
  CONSTRAINT `pid`
    FOREIGN KEY ()
    REFERENCES `qrumb`.`project` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `qrumb`.`tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qrumb`.`tasks` (
  `cid` INT NOT NULL AUTO_INCREMENT,
  `cname` VARCHAR(20) NOT NULL,
  `tid` INT NULL DEFAULT NULL,
  `cdesc` VARCHAR(330) NULL DEFAULT NULL,
  `assign` INT NULL DEFAULT NULL,
  `pid` INT NULL DEFAULT NULL,
  `uid` INT NOT NULL,
  PRIMARY KEY (`cid`, `uid`),
  INDEX `pid_idx` (`pid` ASC),
  INDEX `uid_idx` (`uid` ASC),
  CONSTRAINT `pid`
    FOREIGN KEY (`pid`)
    REFERENCES `qrumb`.`project` (`pid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `uid`
    FOREIGN KEY (`uid`)
    REFERENCES `qrumb`.`people` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `qrumb`.`permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qrumb`.`permissions` (
  `pidx` INT NOT NULL AUTO_INCREMENT,
  `uid` INT NOT NULL,
  `pr_id` INT NOT NULL,
  `permission` INT NOT NULL,
  PRIMARY KEY (`pidx`),
  INDEX `uid_idx` (`uid` ASC),
  INDEX `pid_idx` (`pr_id` ASC),
  CONSTRAINT `uid`
    FOREIGN KEY (`uid`)
    REFERENCES `qrumb`.`people` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `pid`
    FOREIGN KEY (`pr_id`)
    REFERENCES `qrumb`.`project` (`pid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
